DATA:
  data_root: /vulcanscratch/psando/VOC/VOCdevkit/VOC2012
  train_list: /cfarhomes/psando/Documents/semseg/splits/voc2012/train_aug.txt
  val_list: /cfarhomes/psando/Documents/semseg/splits/voc2012/val.txt
  classes: 21

TRAIN:
  arch: psp
  layers: 50
  sync_bn: True  # adopt sync_bn or not
  train_h: 473
  train_w: 473
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0,1,2,3]
  workers: 4  # data loader workers
  batch_size: 32  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 50
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: /vulcanscratch/psando/semseg_experiments/exp/voc2012/pspnet50/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: /cfarhomes/psando/Documents/semseg/splits/voc2012/val.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 473
  test_w: 473
  test_gpu: [0]
  model_path: /vulcanscratch/psando/semseg_experiments/exp/voc2012/pspnet50/model/train_epoch_50.pth  # evaluation model path
